#include <stdio>

extern int
main(void)
{
	#include "my_first_ever_meta_include.meta"
	/*
		Meta.line(f'''
			printf("The included file will have the code that's in this very f-string!\\n");
			printf("... almost. We have to escape some characters, but it's pretty close.\\n");
			for (int i = 0; i < 10; i += 1)
			{{
				printf("%d\\n", i);
			}}
		''')
	*/

	printf("The output above was from code that was generated by the Meta-Preprocessor!\n");
	printf("See the `build` directory for the generated output or `prebuilt` if that's more convenient.\n");
}
